### ISSUE TITLE
Link to Patch is dead

### ISSUE THREAD

**Issue by hilga007** [johnko/ubuntu-14.04.2-desktop-amd64-intel-compute-stick#2]
The Google drive link no longer works

**Comment by johnko** [comment]
oh unfortunately I didn't host it. The instructions were originally from Ian Morrison

**Comment by johnko** [comment]
I think i have the modified version in this repo at https://github.com/johnko/ubuntu-14.04.2-desktop-amd64-intel-compute-stick/blob/master/linuxium-z3735f-patch.sh

**Comment by johnko** [comment]
if you go back in the git history, it might be https://github.com/johnko/ubuntu-14.04.2-desktop-amd64-intel-compute-stick/commit/ff473bdaa6d6a5a4c5c86f3e98255fe7a3faa342#diff-782fe5fdb81ebb9b6eb4b5ac5353cebab709296252602f37a8a455cdb2ac31e2
